version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  print_hello: #print_hello job
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello"
  print_world: #print_world job
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - run: echo "world"

workflows:
  my_workflow:
    jobs:
      - my_job
      - print_hello
      - print_world: 
          requires:
            - print_hello