# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# jobs section
jobs:
  print_hello: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Throw an error
          command: return 1
          when: always
      - run: 
          name: On Failure
          when: on_fail
          command: echo "Job failed"
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow 
  myWorkflow:
    # Run the jobs
    jobs:
      - print_hello
      #- print_world: 
      #    requires:
      #      - print_hello
      #- print_my_name
